name: Build Artifacts

on:
  push:
    branches-ignore:
      - refs/tags/*

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - name: Build artifacts
        run: yarn electron:build
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - name: Build artifacts
        run: yarn electron:build
