name: Publish Artifacts

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Import code signing certificate
        run: |
          echo "${{ secrets.CERT_PUB_MAC }}" | base64 -D > "$HOME/pub.cer"
          echo "${{ secrets.CERT_PRIV_MAC }}" | base64 -D > "$HOME/key.p12"
          sudo security import "$HOME/key.p12" \
            -P "${{ secrets.CERT_PASSWORD }}" \
            -k "/Library/Keychains/System.keychain" \
            -T /usr/bin/codesign
          sudo security add-trusted-cert -d -k "/Library/Keychains/System.keychain" "$HOME/pub.cer"
          security find-identity -v
        if: matrix.os == 'macos-latest'
      - run: yarn install --frozen-lockfile
      - name: Build artifacts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn electron:build --publish always
